# Generated by Django 3.0.7 on 2020-06-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
