# Generated by Django 3.0.7 on 2020-06-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_comments_date_created'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='Comments',
        ),
    ]
