# Generated by Django 3.0.7 on 2020-06-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20200609_1554'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customers',
        ),
    ]
