# Generated by Django 3.0.7 on 2020-06-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20200609_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
